name: Build executables

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
    env:
      EXECUTABLE: autotool-helper

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache-stack
      uses: actions/cache@v2
      if: matrix.os != 'windows-latest'
      env:
        cache-name: stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache-stack (Windows)
      uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      env:
        cache-name: stack-windows
      with:
        path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup Stack
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      uses: mstksg/setup-stack@v2
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ runner.os }}-${{ env.EXECUTABLE }}
        path: .stack-work/install/
